In [2]:
import numpy as np
import pandas as pd

In [3]:
# load dataset and define student_df
import pandas as pd
import seaborn as sns

url = "https://raw.githubusercontent.com/GokuMohandas/Made-With-ML/main/datasets/titanic.csv"
try:
    student_df = pd.read_csv(url, header=0)
except Exception as e:
    print(f"Failed to load from URL ({e}), falling back to seaborn 'titanic' dataset.")
    student_df = sns.load_dataset('titanic')

# normalize column names to avoid case/whitespace issues
student_df.columns = [str(c).strip().lower() for c in student_df.columns]

student_df.head()

Failed to load from URL (HTTP Error 404: Not Found), falling back to seaborn 'titanic' dataset.

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# Creating pandas Series examples with renamed variables
num_list = [1, 2, 3, 4, 5]
mySeriesA = pd.Series(num_list)
mySeriesA

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
# Series with custom index
num_list = [10, 20, 30, 40, 50]
my_index = ['a','b','c','d','e']
mySeriesB = pd.Series(num_list, index=my_index)
print(mySeriesB)
type(mySeriesB)

a    10
b    20
c    30
d    40
e    50
dtype: int64

pandas.core.series.Series

In [6]:
# Mixed-type Series with a custom name
mixed_data = [0.5, 'missing', 404]
idx = ['x','y','z']
mySeriesC = pd.Series(mixed_data, idx, name='MyErrors')
mySeriesC.index.name = 'Index'
print(mySeriesC)

Index
x        0.5
y    missing
z        404
Name: MyErrors, dtype: object

In [7]:
# Series from a dictionary
dict_sample = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 'text'}
mySeriesD = pd.Series(dict_sample, name='Col1')
print(mySeriesD.index)
mySeriesD

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

a     100
b     200
c     300
d     400
e    text
Name: Col1, dtype: object

In [8]:
# Series from list of lists
list_of_rows = [[1,2,3],[4,5,6],[7,8,9]]
idx = [1,2,3]
mySeriesE = pd.Series(list_of_rows, idx)
print(mySeriesE[1])
print(type(mySeriesE[1]))
mySeriesE

[1, 2, 3]
<class 'list'>

1    [1, 2, 3]
2    [4, 5, 6]
3    [7, 8, 9]
dtype: object

In [9]:
# Create DataFrame from Series
data_map = {'ColA': mySeriesD, 'ColB': mySeriesB}
my_dataframe = pd.DataFrame(data_map)
my_dataframe

   ColA  ColB
a   100    10
b   200    20
c   300    30
d   400    40
e  text    50

In [10]:
# DataFrame from dictionaries
dict1 = {'a':1, 'b':2, 'c':3, 'd':4}
dict2 = {'a':'m', 'b':'n', 'c':'o', 'd':'p', 'e':'q'}
combined = {'Left': dict1, 'Right': dict2}
combined_df = pd.DataFrame(combined)
combined_df

   Left Right
a   1.0     m
b   2.0     n
c   3.0     o
d   4.0     p
e   NaN     q

In [11]:
# DataFrame from list of dicts
dict_list = [
	{'x1':1, 'x2':2, 'x3':3, 'x4':4},
	{'x1':5, 'x2':6, 'x3':7},
	{'x1':8, 'x2':9, 'x3':10, 'x4':11, 'x5':12}
]
pd.DataFrame.from_dict(dict_list, orient='columns')

   x1  x2  x3    x4    x5
0   1   2   3   4.0   NaN
1   5   6   7   NaN   NaN
2   8   9  10  11.0  12.0

In [13]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr_df = pd.DataFrame({'A': arr1.ravel(), 'B': arr2.ravel()})
arr_df

   A   B
0  1   7
1  2   8
2  3   9
3  4  10
4  5  11
5  6  12

In [14]:
# Data cleaning example (using renamed vars)
sample_copy = student_df.copy()
for i in range(0, 10000, 100):
		if i in sample_copy.index:
				sample_copy.loc[i, 'Hours Studied'] = np.nan
sample_copy.isnull().sum()

survived           0
pclass             0
sex                0
age              177
sibsp              0
parch              0
fare               0
embarked           2
class              0
who                0
adult_male         0
deck             688
embark_town        2
alive              0
alone              0
Hours Studied    891
dtype: int64

In [15]:
# Drop nulls and duplicates
cleaned = sample_copy.dropna(axis=0)
cleaned = cleaned.drop_duplicates()
cleaned.shape

(0, 16)